import { db } from "./db";
import { channels, movies, plans, faqs, testimonials } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  const [channelCount] = await db.select({ count: sql<number>`count(*)::int` }).from(channels);
  const channelsExist = channelCount.count > 0;

  const channelData = [
    { name: "ESPN", category: "sports", isHd: true, channelNumber: 101 },
    { name: "Sky Sports", category: "sports", isHd: true, channelNumber: 102 },
    { name: "Fox Sports", category: "sports", isHd: true, channelNumber: 103 },
    { name: "beIN Sports", category: "sports", isHd: true, channelNumber: 104 },
    { name: "NBA TV", category: "sports", isHd: true, channelNumber: 105 },
    { name: "NFL Network", category: "sports", isHd: true, channelNumber: 106 },
    { name: "Tennis Channel", category: "sports", isHd: true, channelNumber: 107 },
    { name: "Golf Channel", category: "sports", isHd: true, channelNumber: 108 },
    { name: "HBO", category: "entertainment", isHd: true, channelNumber: 201 },
    { name: "Netflix Live", category: "entertainment", isHd: true, channelNumber: 202 },
    { name: "AMC", category: "entertainment", isHd: true, channelNumber: 203 },
    { name: "FX Network", category: "entertainment", isHd: true, channelNumber: 204 },
    { name: "Comedy Central", category: "entertainment", isHd: true, channelNumber: 205 },
    { name: "Showtime", category: "entertainment", isHd: true, channelNumber: 206 },
    { name: "Paramount", category: "entertainment", isHd: true, channelNumber: 207 },
    { name: "Starz", category: "entertainment", isHd: true, channelNumber: 208 },
    { name: "CNN", category: "news", isHd: true, channelNumber: 301 },
    { name: "BBC World", category: "news", isHd: true, channelNumber: 302 },
    { name: "Al Jazeera", category: "news", isHd: true, channelNumber: 303 },
    { name: "Sky News", category: "news", isHd: true, channelNumber: 304 },
    { name: "Fox News", category: "news", isHd: true, channelNumber: 305 },
    { name: "Reuters TV", category: "news", isHd: true, channelNumber: 306 },
    { name: "MTV", category: "music", isHd: true, channelNumber: 401 },
    { name: "VH1", category: "music", isHd: true, channelNumber: 402 },
    { name: "CMT", category: "music", isHd: false, channelNumber: 403 },
    { name: "BET Music", category: "music", isHd: true, channelNumber: 404 },
    { name: "Music Choice", category: "music", isHd: false, channelNumber: 405 },
    { name: "Cartoon Network", category: "kids", isHd: true, channelNumber: 501 },
    { name: "Nickelodeon", category: "kids", isHd: true, channelNumber: 502 },
    { name: "Disney Channel", category: "kids", isHd: true, channelNumber: 503 },
    { name: "Disney Junior", category: "kids", isHd: true, channelNumber: 504 },
    { name: "Baby TV", category: "kids", isHd: false, channelNumber: 505 },
    { name: "Discovery", category: "education", isHd: true, channelNumber: 601 },
    { name: "National Geographic", category: "education", isHd: true, channelNumber: 602 },
    { name: "History Channel", category: "education", isHd: true, channelNumber: 603 },
    { name: "Science Channel", category: "education", isHd: true, channelNumber: 604 },
    { name: "Smithsonian", category: "education", isHd: true, channelNumber: 605 },
    { name: "Animal Planet", category: "education", isHd: true, channelNumber: 606 },
    { name: "TLC", category: "entertainment", isHd: true, channelNumber: 209 },
    { name: "E! Entertainment", category: "entertainment", isHd: true, channelNumber: 210 },
    { name: "ESPN2", category: "sports", isHd: true, channelNumber: 109 },
    { name: "UFC Fight Pass", category: "sports", isHd: true, channelNumber: 110 },
    { name: "Cricket HD", category: "sports", isHd: true, channelNumber: 111 },
    { name: "WWE Network", category: "sports", isHd: true, channelNumber: 112 },
    { name: "Eurosport", category: "sports", isHd: true, channelNumber: 113 },
    { name: "DAZN", category: "sports", isHd: true, channelNumber: 114 },
    { name: "HBO Max", category: "entertainment", isHd: true, channelNumber: 211 },
    { name: "Peacock", category: "entertainment", isHd: true, channelNumber: 212 },
    { name: "Bravo", category: "entertainment", isHd: true, channelNumber: 213 },
    { name: "A&E", category: "entertainment", isHd: true, channelNumber: 214 },
    { name: "Syfy", category: "entertainment", isHd: true, channelNumber: 215 },
    { name: "USA Network", category: "entertainment", isHd: true, channelNumber: 216 },
    { name: "MSNBC", category: "news", isHd: true, channelNumber: 307 },
    { name: "CNBC", category: "news", isHd: true, channelNumber: 308 },
    { name: "ABC News", category: "news", isHd: true, channelNumber: 309 },
    { name: "CBS News", category: "news", isHd: true, channelNumber: 310 },
    { name: "Fuse", category: "music", isHd: true, channelNumber: 406 },
    { name: "Trace Urban", category: "music", isHd: true, channelNumber: 407 },
    { name: "Stingray Music", category: "music", isHd: false, channelNumber: 408 },
    { name: "PBS Kids", category: "kids", isHd: true, channelNumber: 506 },
    { name: "Boomerang", category: "kids", isHd: true, channelNumber: 507 },
    { name: "Nick Jr", category: "kids", isHd: true, channelNumber: 508 },
    { name: "Discovery Kids", category: "kids", isHd: true, channelNumber: 509 },
    { name: "BBC Earth", category: "education", isHd: true, channelNumber: 607 },
    { name: "Curiosity Stream", category: "education", isHd: true, channelNumber: 608 },
    { name: "PBS", category: "education", isHd: true, channelNumber: 609 },
    { name: "Travel Channel", category: "education", isHd: true, channelNumber: 610 },
  ];

  if (!channelsExist) {
    await db.insert(channels).values(channelData);
  }

  const [movieCount] = await db.select({ count: sql<number>`count(*)::int` }).from(movies);
  if (movieCount.count === 0) {
    await db.insert(movies).values([
      { title: "The Dark Knight", genre: "action", year: 2008, rating: "9.0", duration: "2h 32m", description: "A gripping tale of heroism and chaos in a city on the edge of destruction." },
      { title: "Inception", genre: "sci-fi", year: 2010, rating: "8.8", duration: "2h 28m", description: "A mind-bending journey through layers of dreams and reality." },
      { title: "Interstellar", genre: "sci-fi", year: 2014, rating: "8.7", duration: "2h 49m", description: "A team of explorers travel beyond our galaxy to find humanity's new home." },
      { title: "The Shawshank Redemption", genre: "drama", year: 1994, rating: "9.3", duration: "2h 22m", description: "Two imprisoned men bond over years, finding solace and eventual redemption." },
      { title: "Parasite", genre: "thriller", year: 2019, rating: "8.5", duration: "2h 12m", description: "A poor family schemes to infiltrate a wealthy household with devastating consequences." },
      { title: "John Wick: Chapter 4", genre: "action", year: 2023, rating: "7.8", duration: "2h 49m", description: "The legendary hitmaker takes on his most lethal adversaries yet." },
      { title: "Oppenheimer", genre: "drama", year: 2023, rating: "8.9", duration: "3h 0m", description: "The story of the man who built the atomic bomb and changed the world forever." },
      { title: "Dune: Part Two", genre: "sci-fi", year: 2024, rating: "8.6", duration: "2h 46m", description: "Paul Atreides unites with the Fremen to wage war against House Harkonnen." },
      { title: "Spider-Man: Beyond the Spider-Verse", genre: "animation", year: 2027, rating: "8.2", duration: "2h 30m", description: "The web-slinger faces a multiverse threat that could unravel all of reality." },
      { title: "The Batman", genre: "action", year: 2022, rating: "7.8", duration: "2h 56m", description: "Gotham's dark protector faces a new villain threatening to expose the city's darkest secrets." },
      { title: "The Conjuring: Last Rites", genre: "horror", year: 2025, rating: "7.5", duration: "1h 52m", description: "The Warrens face their most terrifying case yet in this supernatural thriller." },
      { title: "Inside Out 2", genre: "animation", year: 2024, rating: "7.6", duration: "1h 36m", description: "Riley's emotions navigate the complexities of young adulthood." },
      { title: "Gladiator II", genre: "action", year: 2024, rating: "8.1", duration: "2h 28m", description: "A new warrior rises in the arena to challenge the might of the Roman Empire." },
      { title: "The Holdovers", genre: "comedy", year: 2023, rating: "7.9", duration: "2h 13m", description: "A curmudgeonly instructor at a boarding school remains with a student over Christmas break." },
      { title: "A Quiet Place: Day One", genre: "horror", year: 2024, rating: "7.6", duration: "1h 39m", description: "The origin story of the alien invasion that silenced the world." },
      { title: "Mission: Impossible - Dead Reckoning Part One", genre: "action", year: 2023, rating: "7.7", duration: "2h 43m", description: "Ethan Hunt faces his most personal and dangerous mission yet." },
      { title: "The Grand Budapest Hotel", genre: "comedy", year: 2014, rating: "8.1", duration: "1h 39m", description: "A concierge at a famous European hotel gets caught up in theft and murder." },
      { title: "Alien: Romulus", genre: "horror", year: 2024, rating: "7.4", duration: "1h 59m", description: "A group of young colonists encounter the most terrifying life form in the universe." },
      { title: "Wonka", genre: "fantasy", year: 2023, rating: "7.1", duration: "1h 56m", description: "A magical journey into the most extraordinary chocolate factory ever imagined." },
      { title: "Nosferatu", genre: "horror", year: 2024, rating: "8.0", duration: "2h 12m", description: "A gothic tale of obsession between a haunted young woman and a terrifying vampire." },
      { title: "Thunderbolts*", genre: "action", year: 2025, rating: "7.9", duration: "2h 15m", description: "A team of antiheroes is assembled for a mission that could save or doom the world." },
      { title: "The Wild Robot", genre: "animation", year: 2024, rating: "8.5", duration: "1h 42m", description: "A robot must learn to survive in the wilderness and becomes a parent to a baby goose." },
      { title: "Furiosa: A Mad Max Saga", genre: "action", year: 2024, rating: "8.3", duration: "2h 28m", description: "The origin story of the warrior Furiosa before she teamed up with Mad Max." },
      { title: "Deadpool & Wolverine", genre: "action", year: 2024, rating: "8.4", duration: "2h 7m", description: "The merc with a mouth teams up with Wolverine in a multiverse adventure." },
      { title: "Twisters", genre: "action", year: 2024, rating: "7.3", duration: "2h 2m", description: "A new generation of storm chasers faces the most powerful tornadoes ever recorded." },
      { title: "Beetlejuice Beetlejuice", genre: "comedy", year: 2024, rating: "7.5", duration: "1h 44m", description: "The ghost with the most returns for another round of afterlife chaos." },
      { title: "Kingdom of the Planet of the Apes", genre: "sci-fi", year: 2024, rating: "7.8", duration: "2h 25m", description: "A new ape leader rises in a world where apes rule and humans struggle to survive." },
      { title: "Joker: Folie \u00e0 Deux", genre: "drama", year: 2024, rating: "7.1", duration: "2h 18m", description: "Arthur Fleck finds love and music in the madness of Arkham Asylum." },
      { title: "Venom: The Last Dance", genre: "action", year: 2024, rating: "7.0", duration: "1h 49m", description: "Eddie Brock and Venom face their final adventure against an alien invasion." },
      { title: "The Substance", genre: "horror", year: 2024, rating: "7.9", duration: "2h 20m", description: "A fading celebrity discovers a mysterious substance that creates a younger version of herself." },
      { title: "Moana 2", genre: "animation", year: 2024, rating: "7.6", duration: "1h 40m", description: "Moana sets sail on a brand new voyage with a crew of unlikely seafarers." },
      { title: "Wicked", genre: "fantasy", year: 2024, rating: "8.2", duration: "2h 40m", description: "The untold story of the witches of Oz before Dorothy arrived." },
      { title: "Sonic the Hedgehog 3", genre: "animation", year: 2024, rating: "7.4", duration: "1h 50m", description: "Sonic teams up with an unlikely ally to stop a powerful new enemy." },
      { title: "Captain America: Brave New World", genre: "action", year: 2025, rating: "7.7", duration: "2h 10m", description: "Sam Wilson takes on the mantle of Captain America in a world on the brink." },
      { title: "28 Years Later", genre: "horror", year: 2025, rating: "8.0", duration: "2h 15m", description: "Nearly three decades after the rage virus, a new chapter of survival begins." },
      { title: "Ballerina", genre: "action", year: 2025, rating: "7.6", duration: "1h 55m", description: "A young assassin seeks revenge in the world of John Wick." },
      { title: "Lilo & Stitch", genre: "comedy", year: 2025, rating: "7.8", duration: "1h 48m", description: "A live-action reimagining of the beloved story of a girl and her alien friend." },
      { title: "The Fantastic Four: First Steps", genre: "action", year: 2025, rating: "7.5", duration: "2h 20m", description: "Marvel's first family takes their first steps into the larger universe." },
      { title: "Superman", genre: "action", year: 2025, rating: "8.1", duration: "2h 35m", description: "The Man of Steel returns in a brand new origin story for a new generation." },
      { title: "Blade Runner 2049", genre: "sci-fi", year: 2017, rating: "8.0", duration: "2h 44m", description: "A new blade runner uncovers a conspiracy that threatens the future of both humans and replicants." },
      { title: "The Accountant 2", genre: "thriller", year: 2025, rating: "7.4", duration: "2h 5m", description: "The world's most dangerous accountant returns to untangle a deadly financial web." },
      { title: "Paddington in Peru", genre: "comedy", year: 2025, rating: "8.0", duration: "1h 46m", description: "Paddington travels to Peru on a mission to visit his Aunt Lucy." },
      { title: "Snow White", genre: "fantasy", year: 2025, rating: "6.8", duration: "1h 55m", description: "A live-action retelling of the classic fairy tale about a princess and seven dwarfs." },
      { title: "The Crow", genre: "action", year: 2024, rating: "6.5", duration: "1h 51m", description: "A man is resurrected to avenge his own murder and save the love of his life." },
      { title: "Kraven the Hunter", genre: "action", year: 2024, rating: "6.9", duration: "2h 7m", description: "The origin story of one of Marvel's most iconic villains." },
      { title: "IF", genre: "fantasy", year: 2024, rating: "7.2", duration: "1h 44m", description: "A girl discovers she can see imaginary friends that others have forgotten." },
      { title: "Despicable Me 4", genre: "animation", year: 2024, rating: "7.1", duration: "1h 34m", description: "Gru and the Minions face a new villain with a connection to Gru's past." },
      { title: "Bad Boys: Ride or Die", genre: "action", year: 2024, rating: "7.3", duration: "1h 55m", description: "Miami's finest return for one more ride against a powerful drug cartel." },
      { title: "Trap", genre: "thriller", year: 2024, rating: "7.0", duration: "1h 45m", description: "A father takes his daughter to a concert that turns out to be a trap for a serial killer." },
      { title: "Speak No Evil", genre: "horror", year: 2024, rating: "7.4", duration: "1h 50m", description: "A family's dream vacation becomes a terrifying nightmare at the hands of their hosts." },
      { title: "It Ends with Us", genre: "romance", year: 2024, rating: "7.2", duration: "2h 10m", description: "A woman must choose between the man she loves and breaking the cycle of abuse." },
      { title: "Fly Me to the Moon", genre: "comedy", year: 2024, rating: "6.9", duration: "2h 12m", description: "A marketing specialist is hired to stage a fake moon landing alongside the real mission." },
      { title: "The Garfield Movie", genre: "animation", year: 2024, rating: "6.5", duration: "1h 41m", description: "Garfield is forced on an outdoor adventure with his long-lost father." },
      { title: "The Watchers", genre: "horror", year: 2024, rating: "6.8", duration: "1h 42m", description: "A group of strangers are trapped in a forest and watched by mysterious creatures." },
      { title: "Civil War", genre: "drama", year: 2024, rating: "7.5", duration: "1h 49m", description: "Journalists navigate a dystopian future America torn apart by civil conflict." },
      { title: "Abigail", genre: "horror", year: 2024, rating: "7.3", duration: "1h 49m", description: "A group of kidnappers discover their young captive is not what she seems." },
      { title: "Monkey Man", genre: "action", year: 2024, rating: "7.6", duration: "2h 1m", description: "An anonymous young man unleashes a campaign of vengeance against corrupt leaders." },
      { title: "The Fall Guy", genre: "action", year: 2024, rating: "7.4", duration: "2h 6m", description: "A stuntman is pulled back into action when the star of a movie goes missing." },
      { title: "Challengers", genre: "drama", year: 2024, rating: "8.0", duration: "2h 11m", description: "A tennis prodigy turned coach transforms her husband into a champion." },
      { title: "Hit Man", genre: "comedy", year: 2024, rating: "7.8", duration: "1h 53m", description: "A professor moonlighting as a fake hitman for police stings gets too deep into his role." },
      { title: "Megalopolis", genre: "drama", year: 2024, rating: "6.5", duration: "2h 18m", description: "An architect wants to rebuild New York as a utopia after a devastating disaster." },
      { title: "The Ministry of Ungentlemanly Warfare", genre: "action", year: 2024, rating: "7.2", duration: "2h 0m", description: "A secret British WWII organization recruits a team of unconventional soldiers." },
      { title: "Godzilla x Kong: The New Empire", genre: "action", year: 2024, rating: "7.0", duration: "1h 55m", description: "Two titans team up against a colossal undiscovered threat hidden within our world." },
      { title: "Back in Action", genre: "action", year: 2025, rating: "6.8", duration: "1h 54m", description: "Former CIA spies are pulled back into espionage when their cover is blown." },
      { title: "The Electric State", genre: "sci-fi", year: 2025, rating: "7.3", duration: "2h 10m", description: "A teenager and her robot companion journey across a retro-futuristic America." },
      { title: "Havoc", genre: "action", year: 2025, rating: "7.5", duration: "2h 0m", description: "A bruised detective navigates the criminal underworld to rescue a politician's son." },
      { title: "Wolf Man", genre: "horror", year: 2025, rating: "6.9", duration: "1h 43m", description: "A father moves his family to a remote farmhouse and begins a terrifying transformation." },
      { title: "Companion", genre: "thriller", year: 2025, rating: "7.1", duration: "1h 37m", description: "An AI companion turns deadly when it becomes too attached to its owner." },
      { title: "Warfare", genre: "drama", year: 2025, rating: "8.1", duration: "1h 45m", description: "A visceral and immersive look at a Navy SEAL operation in Ramadi, Iraq." },
      { title: "Presence", genre: "horror", year: 2025, rating: "7.0", duration: "1h 25m", description: "A family moves into a new house unaware that an unseen presence watches their every move." },
      { title: "Wake Up Dead Man: A Knives Out Mystery", genre: "mystery", year: 2025, rating: "8.0", duration: "2h 15m", description: "Detective Blanc returns to solve a murder on a remote island retreat." },
      { title: "Black Bag", genre: "thriller", year: 2025, rating: "7.6", duration: "1h 53m", description: "An intelligence operative suspects his wife may be a traitor." },
      { title: "Sinners", genre: "horror", year: 2025, rating: "7.8", duration: "2h 17m", description: "Twin brothers return to their hometown and encounter an ancient evil." },
      { title: "Mickey 17", genre: "sci-fi", year: 2025, rating: "7.5", duration: "2h 10m", description: "A disposable employee on a human expedition to colonize an ice world." },
      { title: "Until Dawn", genre: "horror", year: 2025, rating: "6.7", duration: "1h 43m", description: "A group of friends face a nightmare scenario where their choices determine who survives." },
      { title: "Materialists", genre: "romance", year: 2025, rating: "7.2", duration: "1h 55m", description: "A Manhattan matchmaker's personal life becomes as complicated as her clients'." },
      { title: "Death of a Unicorn", genre: "comedy", year: 2025, rating: "7.0", duration: "1h 48m", description: "A father and daughter accidentally hit a unicorn, setting off a chain of fantastical events." },
      { title: "The Woman in the Yard", genre: "horror", year: 2025, rating: "6.8", duration: "1h 38m", description: "A grieving widow notices a mysterious woman standing in her yard who refuses to leave." },
      { title: "Elio", genre: "animation", year: 2025, rating: "7.4", duration: "1h 39m", description: "An underdog kid accidentally becomes the intergalactic ambassador for Earth." },
      { title: "Jee Aayan Nu", genre: "drama", year: 2002, rating: "7.5", duration: "2h 30m", description: "A Punjabi NRI returns to India and confronts the reality of immigrant life in Canada.", posterUrl: "https://image.tmdb.org/t/p/w500/f6BCmJ9fPXk1y3Ywowh4NmnIFkq.jpg" },
      { title: "Mel Karade Rabba", genre: "comedy", year: 2010, rating: "7.2", duration: "2h 15m", description: "A comedy about two families brought together by an unlikely love story in Punjab.", posterUrl: "https://image.tmdb.org/t/p/w500/ww2a4rnSaKrHvkDL2eYVglMQRZR.jpg" },
      { title: "Jihne Mera Dil Luteya", genre: "romance", year: 2011, rating: "7.4", duration: "2h 20m", description: "Two college friends compete for the love of a charming girl at Patiala University.", posterUrl: "https://image.tmdb.org/t/p/w500/8X4OeRZURzbreAG0GT4vnv4Pp2g.jpg" },
      { title: "Carry On Jatta", genre: "comedy", year: 2012, rating: "7.8", duration: "2h 25m", description: "A young man pretends to be an orphan to marry the girl of his dreams, leading to hilarious chaos.", posterUrl: "https://image.tmdb.org/t/p/w500/3KJ8UiNloo0Un2osnQOuyXfqNO2.jpg" },
      { title: "Jatt & Juliet", genre: "comedy", year: 2012, rating: "7.9", duration: "2h 22m", description: "A mischievous Jatt and a modern Punjabi girl clash on their way to Canada.", posterUrl: "https://image.tmdb.org/t/p/w500/sWheGtsztva6pVksRorg0mWC1M6.jpg" },
      { title: "Jatt & Juliet 2", genre: "comedy", year: 2013, rating: "7.7", duration: "2h 18m", description: "A constable goes to Canada to bring back the commissioners daughter but falls in love with her.", posterUrl: "https://image.tmdb.org/t/p/w500/yJmq1RjPOFmiyfHOjjta7qF73ph.jpg" },
      { title: "Punjab 1984", genre: "drama", year: 2014, rating: "8.5", duration: "2h 20m", description: "A mothers desperate search for her missing son during the dark era of 1984 Punjab.", posterUrl: "https://image.tmdb.org/t/p/w500/yJcg6qaDFok73SC353u4oEYpkvF.jpg" },
      { title: "Angrej", genre: "romance", year: 2015, rating: "8.3", duration: "2h 35m", description: "A tangled love story set in pre-independence rural Punjab circa 1945.", posterUrl: "https://image.tmdb.org/t/p/w500/eukKHm776O4IujOpElzfuzDNhA9.jpg" },
      { title: "Sardaarji", genre: "comedy", year: 2015, rating: "7.5", duration: "2h 20m", description: "A ghost hunter uses bottles to capture troublesome spirits in Punjab.", posterUrl: "https://image.tmdb.org/t/p/w500/f44yO1FafCLn0KM75LFRnFRo3Yn.jpg" },
      { title: "Ardaas", genre: "drama", year: 2016, rating: "8.4", duration: "2h 25m", description: "A city teacher finds alcoholism and lack of faith among the locals in his new rural posting.", posterUrl: "https://image.tmdb.org/t/p/w500/ch6dE7bXJELXUM5QA48aoqx2ojH.jpg" },
      { title: "Nikka Zaildar", genre: "comedy", year: 2016, rating: "7.3", duration: "2h 10m", description: "A young man concocts a scheme to marry a reluctant fellow student in Punjab.", posterUrl: "https://image.tmdb.org/t/p/w500/dtz8GJTffTscT6Ere4que4tylhk.jpg" },
      { title: "Sardaarji 2", genre: "comedy", year: 2016, rating: "7.2", duration: "2h 18m", description: "Farmer Jaggi travels to Australia to save his village and ends up kidnapping a girl from her wedding.", posterUrl: "https://image.tmdb.org/t/p/w500/xqTok7CmflNocawmahbz9PX498j.jpg" },
      { title: "Manje Bistre", genre: "comedy", year: 2017, rating: "7.6", duration: "2h 15m", description: "A young man tries to woo a girl whose marriage to another has already been fixed during a Punjabi wedding.", posterUrl: "https://image.tmdb.org/t/p/w500/m7YpsaBbcTpYPPQXlzFGaSnUIN3.jpg" },
      { title: "Rabb Da Radio", genre: "drama", year: 2017, rating: "8.2", duration: "2h 20m", description: "A heartwarming love story set in 1980s Punjab between two cousins whose bond defies family opposition.", posterUrl: "https://image.tmdb.org/t/p/w500/AbTxYS1cU3IYjIWbJ3YcWRwX8jt.jpg" },
      { title: "Nikka Zaildar 2", genre: "comedy", year: 2017, rating: "7.1", duration: "2h 5m", description: "Set in the 80s, a man has an affair with his nephews teacher but gets married to another girl.", posterUrl: "https://image.tmdb.org/t/p/w500/vdlCP4XQJ2S0E6q5r2OZ9TBXFvr.jpg" },
      { title: "Carry On Jatta 2", genre: "comedy", year: 2018, rating: "7.5", duration: "2h 30m", description: "The hilarious sequel with more confusion, mistaken identities, and Punjabi comedy.", posterUrl: "https://image.tmdb.org/t/p/w500/bQju8zpjUaOIqyl7qkL9UwNA5vh.jpg" },
      { title: "Qismat", genre: "romance", year: 2018, rating: "8.0", duration: "2h 18m", description: "A beautiful love story that explores the depths of love, sacrifice and destiny.", posterUrl: "https://image.tmdb.org/t/p/w500/nlvV8hF1YCVazGg8PiLO004I2of.jpg" },
      { title: "Dakuaan Da Munda", genre: "crime", year: 2018, rating: "7.8", duration: "2h 15m", description: "Based on the true story of a journalist who overcame drugs and crime to become an inspiration.", posterUrl: "https://image.tmdb.org/t/p/w500/f8hS7PeaDefxFAUdBh6r75rYQN4.jpg" },
      { title: "Shadaa", genre: "comedy", year: 2019, rating: "7.6", duration: "2h 22m", description: "A young man seeks his perfect match amid pressure from his parents to get married quickly.", posterUrl: "https://image.tmdb.org/t/p/w500/saZ5hon73b7BgbRWNpUC0h6uQM6.jpg" },
      { title: "Chal Mera Putt", genre: "comedy", year: 2019, rating: "8.1", duration: "2h 15m", description: "A group of Punjabi and Pakistani immigrants share laughs and struggles in England.", posterUrl: "https://image.tmdb.org/t/p/w500/i4ckFOOeyvU3EGnxbARsoORwbCT.jpg" },
      { title: "Ardaas Karaan", genre: "drama", year: 2019, rating: "8.3", duration: "2h 30m", description: "Three elderly men try to instill values in their families during times of conflict.", posterUrl: "https://image.tmdb.org/t/p/w500/1AyQxB4IObBjQkRcA0ttnSGs5rA.jpg" },
      { title: "Manje Bistre 2", genre: "comedy", year: 2019, rating: "7.0", duration: "2h 18m", description: "Sukhi goes from India to Canada to attend his cousins big fat traditional Punjabi wedding.", posterUrl: "https://image.tmdb.org/t/p/w500/ghUJt13ituoiZysa6hMJTH9w8s4.jpg" },
      { title: "Nikka Zaildar 3", genre: "comedy", year: 2019, rating: "7.0", duration: "2h 10m", description: "Nikkas fathers soul enters his body following his death, leading to comedic chaos.", posterUrl: "https://image.tmdb.org/t/p/w500/msWQ51cB0H25sYHTmkAp4sQfVdP.jpg" },
      { title: "Rabb Da Radio 2", genre: "drama", year: 2019, rating: "7.8", duration: "2h 15m", description: "Manjinder and his wife Guddi vow to reunite an estranged family of four brothers.", posterUrl: "https://image.tmdb.org/t/p/w500/1jmBM8n7onKt9RbK9yJkkr4GJIM.jpg" },
      { title: "Sufna", genre: "romance", year: 2020, rating: "8.0", duration: "2h 10m", description: "A young man from a humble background achieves his dreams with a girl as his strength and inspiration.", posterUrl: "https://image.tmdb.org/t/p/w500/ozso0mV2H6Yke5L6mgZnripGwez.jpg" },
      { title: "Honsla Rakh", genre: "comedy", year: 2021, rating: "7.5", duration: "2h 20m", description: "A single father attempts to find love and a mom for his 7-year-old son.", posterUrl: "https://image.tmdb.org/t/p/w500/2qyTW8y0GR2LNgSbPUZfbbxXPyy.jpg" },
      { title: "Qismat 2", genre: "romance", year: 2021, rating: "7.8", duration: "2h 25m", description: "A story about unrequited love, heartbreak, and the shapes love takes in our lives.", posterUrl: "https://image.tmdb.org/t/p/w500/tze9VKYpS02E0h6A0RvSb9jw6FI.jpg" },
      { title: "Saunkan Saunkne", genre: "comedy", year: 2022, rating: "7.6", duration: "2h 15m", description: "A couple married for 7 years faces comic situations when the husband marries his wifes sister.", posterUrl: "https://image.tmdb.org/t/p/w500/rMAreVJF8PxvKFSUNsTYyCuJdTi.jpg" },
      { title: "Dakuaan Da Munda 2", genre: "crime", year: 2022, rating: "7.4", duration: "2h 18m", description: "The autobiography of Manga Singh Antal, a young Kabaddi player who became a drug addict and found redemption.", posterUrl: "https://image.tmdb.org/t/p/w500/aBaBWIkMm6QIa4kee5zB1YRh5tW.jpg" },
      { title: "Amar Singh Chamkila", genre: "drama", year: 2024, rating: "8.5", duration: "2h 10m", description: "A humble singers brash lyrics ignite fame and fury across Punjab before his untimely death.", posterUrl: "https://image.tmdb.org/t/p/w500/t9wSGgaPfbGUBBlne7xw8GaArvu.jpg" },
      { title: "Jatt & Juliet 3", genre: "comedy", year: 2024, rating: "7.8", duration: "2h 20m", description: "A police officer aspires to marry his well-off boss and joins her on a trip to the UK.", posterUrl: "https://image.tmdb.org/t/p/w500/E7gIlyFSUh7pmzWF3uE1UgVFzN.jpg" },
      { title: "Ardaas Sarbat De Bhale Di", genre: "drama", year: 2024, rating: "8.0", duration: "2h 25m", description: "Gurmukh Singh and diverse individuals embark on a shared pilgrimage to Sri Hazur Sahib.", posterUrl: "https://image.tmdb.org/t/p/w500/ns9fR4y3mY9kHPyWyJmxlboq3Bi.jpg" },
      { title: "Manje Bistre 3", genre: "comedy", year: 2024, rating: "7.2", duration: "2h 18m", description: "The third installment revolving around Punjabi wedding culture and family fun.", posterUrl: "https://image.tmdb.org/t/p/w500/gLjMyYAS0JCmS2upIvleFo5OJf5.jpg" },
      { title: "Rabb Da Radio 3", genre: "drama", year: 2024, rating: "7.6", duration: "2h 15m", description: "The beloved family saga continues with more heartfelt drama and rural Punjab charm.", posterUrl: "https://image.tmdb.org/t/p/w500/1RUIGzLgUBcz9M1wDy63L1Qc6Co.jpg" },
      { title: "Kaale Angrej", genre: "drama", year: 2024, rating: "7.0", duration: "2h 10m", description: "A Punjabi film exploring social issues directed and written by Santokh Takhar.", posterUrl: "https://image.tmdb.org/t/p/w500/mwkNkShyPqxv7SXtD4cMOVjXqTc.jpg" },
      { title: "Sardaarji 3", genre: "comedy", year: 2025, rating: "7.8", duration: "2h 22m", description: "Legendary ghosthunter Jaggi returns with ghost buddy Pinky to take on a haunted English castle.", posterUrl: "https://image.tmdb.org/t/p/w500/ncLqJpmFlTxHbgeVRrdKZrHGfUl.jpg" },
      { title: "Nikka Zaildar 4", genre: "comedy", year: 2025, rating: "7.2", duration: "2h 10m", description: "A Punjabi mans problems begin when he marries a strange woman.", posterUrl: "https://image.tmdb.org/t/p/w500/dPbyKQaYwEIE6qzuM2snwOlZbGj.jpg" },
      { title: "Dakuaan Da Munda 3", genre: "action", year: 2025, rating: "7.5", duration: "2h 15m", description: "An orphaned boxer from a criminal family battles addiction and seeks redemption.", posterUrl: "https://image.tmdb.org/t/p/w500/xhuzfeyG4qml1c2KDKeaZhbxO1u.jpg" },
      { title: "Angreji Aali Madam", genre: "drama", year: 2025, rating: "7.3", duration: "2h 12m", description: "Harman searches for his childhood teacher to discover a truth that changes everything.", posterUrl: "https://image.tmdb.org/t/p/w500/hjnj4JdIPLwuwbPqemqabf451tp.jpg" },
      { title: "Sarbala Ji", genre: "comedy", year: 2025, rating: "7.4", duration: "2h 18m", description: "A harmless wedding prank turns into a wild curse leading to runaway grooms and bandits.", posterUrl: "https://image.tmdb.org/t/p/w500/eCERukldal4nrbupGdOzviAv5cQ.jpg" },
    ]);
  }

  const [planCount] = await db.select({ count: sql<number>`count(*)::int` }).from(plans);
  if (planCount.count > 0) {
    console.log("Database already seeded!");
    return;
  }

  await db.insert(plans).values([
    {
      name: "Standard",
      price: "15.99",
      description: "1 Month",
      features: ["46,000+ Live TV Channels", "Unlimited Movies", "Unlimited Web Series", "Full HD & 4K Quality", "1 Connection", "EPG Included", "Anti-Buffer Technology"],
      isPopular: false,
      sortOrder: 1,
    },
    {
      name: "Premium",
      price: "39.99",
      description: "3 Months",
      features: ["46,000+ Live TV Channels", "Unlimited Movies", "Unlimited Web Series", "Full HD & 4K Quality", "1 Connection", "EPG Included", "Anti-Buffer Technology"],
      isPopular: true,
      sortOrder: 2,
    },
    {
      name: "Pro",
      price: "54.99",
      description: "6 Months",
      features: ["46,000+ Live TV Channels", "Unlimited Movies", "Unlimited Web Series", "Full HD & 4K Quality", "1 Connection", "EPG Included", "Anti-Buffer Technology", "Priority Support"],
      isPopular: false,
      sortOrder: 3,
    },
    {
      name: "Ultimate",
      price: "69.99",
      description: "12 Months",
      features: ["46,000+ Live TV Channels", "Unlimited Movies", "Unlimited Web Series", "Full HD & 4K Quality", "2 Connections", "EPG Included", "Anti-Buffer Technology", "24/7 Priority Support"],
      isPopular: false,
      sortOrder: 4,
    },
  ]);

  await db.insert(faqs).values([
    { question: "What is StreamXHD?", answer: "StreamXHD is a next-generation IPTV streaming platform that delivers 46,000+ live TV channels, movies, and shows directly to your devices. We use cutting-edge technology to ensure crystal-clear quality and zero buffering.", category: "general", sortOrder: 1 },
    { question: "How do I get started?", answer: "Getting started is easy! Simply choose a plan that fits your needs, create an account, and start streaming within minutes. We offer a free 24-hour trial so you can experience StreamXHD before committing.", category: "general", sortOrder: 2 },
    { question: "What devices are supported?", answer: "StreamXHD works on Smart TVs (Samsung, LG, Sony), Android & iOS phones and tablets, Amazon Fire Stick, Apple TV, Roku, web browsers, and more. Any device with an internet connection can stream StreamXHD.", category: "general", sortOrder: 3 },
    { question: "Is there a contract or commitment?", answer: "No! StreamXHD is completely contract-free. You can cancel your subscription at any time without any penalties or hidden fees. We believe in earning your business every month.", category: "general", sortOrder: 4 },
    { question: "What internet speed do I need?", answer: "For HD streaming, we recommend at least 10 Mbps. For 4K Ultra HD, we recommend 25 Mbps or higher. StreamXHD automatically adjusts quality based on your connection to ensure smooth playback.", category: "technical", sortOrder: 5 },
    { question: "Can I watch on multiple devices at once?", answer: "Yes! Depending on your plan, you can stream on multiple devices. The Standard plan supports 1 device, Premium Pro supports 1 device, and Ultimate supports 2 concurrent streams.", category: "technical", sortOrder: 6 },
    { question: "Do you offer an Electronic Program Guide (EPG)?", answer: "Absolutely! All plans include a full Electronic Program Guide (EPG) so you can easily see what's playing now, what's coming up, and plan your viewing schedule in advance.", category: "technical", sortOrder: 7 },
    { question: "What if I experience buffering or quality issues?", answer: "First, check your internet connection speed. If the issue persists, try restarting the app or clearing the cache. Our 24/7 support team is always available to help troubleshoot any technical issues.", category: "technical", sortOrder: 8 },
    { question: "How does billing work?", answer: "StreamXHD offers flexible billing options. You can choose from 1 Month, 3 Months, 6 Months, or 1 Year subscription plans. All payments are processed securely and you'll receive a receipt via email. Longer plans offer better value with greater savings.", category: "billing", sortOrder: 9 },
    { question: "Can I upgrade or downgrade my plan?", answer: "Yes, you can change your plan at any time. Upgrades take effect immediately and you'll be charged the prorated difference. Downgrades take effect at the start of your next billing cycle.", category: "billing", sortOrder: 10 },
    { question: "Are there any hidden fees?", answer: "Absolutely not. The price you see is the price you pay. There are no setup fees, equipment rental fees, or hidden charges. What you see on our pricing page is exactly what you'll be billed.", category: "billing", sortOrder: 12 },
  ]);

  await db.insert(testimonials).values([
    { name: "Ahmed Khan", role: "Sports Fan", content: "StreamXHD has completely transformed how I watch sports. The 4K quality and zero buffering make it feel like I'm at the stadium! I've cancelled all my cable subscriptions.", rating: 5 },
    { name: "Sarah Williams", role: "Movie Enthusiast", content: "The VOD library is incredible. I cancelled all my other subscriptions because StreamXHD has everything I need in one place. The interface is clean and easy to navigate.", rating: 5 },
    { name: "David Chen", role: "Family User", content: "Perfect for our family of five. Kids love the cartoon channels, my wife enjoys dramas, and I get all the sports channels. The parental controls give us peace of mind.", rating: 5 },
    { name: "Maria Garcia", role: "Tech Professional", content: "As someone who works in tech, I appreciate the quality of StreamXHD's infrastructure. The 4K streaming is flawless and the app performance across all my devices is outstanding.", rating: 5 },
    { name: "James Wilson", role: "Business Owner", content: "We use StreamXHD in our hotel chain for guest entertainment. The reliability and channel variety have significantly improved our guest satisfaction scores.", rating: 5 },
  ]);

  console.log("Database seeded successfully!");
}
